### ISSUE TITLE
用户自定义词典不能导入

### ISSUE THREAD

**Issue by tersis1111** [NLPchina/nlp-lang#11]
1.在library.properties里面指定用户自定义词典路径，发现自定义词不能导入
2.利用该方法也不能实现：UserDefineLibrary.loadFile
只有使用UserDefineLibrary.insertWord这种方法插入的用户词可以使用

**Comment by ansjsun** [comment]
你吃点个事可能不对。。不要用windows 记事本编辑。。。需要utf8编码

**Comment by tersis1111** [comment]
确实是编码的问题，utf8就好了
