### ISSUE TITLE
pom.xml 中 maven-compiler-plugin 配置需要修改

### ISSUE THREAD

**Issue by patrickhe** [NLPchina/nlp-lang#13]
现在指定 source 和 target 都是1.6，而代码中使用了 try-with-resources 语法（例如DoubleArrayTire.java），会导致 mvn install 之类的命令执行失败。
把 source 和 target 改成7、8或者不指定的话，在本地就可以编译了。

**Comment by ansjsun** [comment]
没有吧。。应该只定义了编译后的jar包兼容好的我去检查下

**Comment by ansjsun** [comment]
感谢是有这个问题。遮就修正再次感谢
