### ISSUE TITLE
文档中的从词典删除单词演示代码有误

### ISSUE THREAD

**Issue by node** [NLPchina/nlp-lang#15]
http://www.nlpcn.org/docs/7/c0815cc4-4377-4990-a7a8-2325d76f260c

“基本tire树”中的“删除一个单词”，演示代码为
  Library.insertWord(forest, "中国");

实际应为
  Library.removeWord(forest, "中国");

**Comment by ansjsun** [comment]
谢谢兄台提醒。额 将来打算把网站改版了。。。那个错误先保留吧
