### ISSUE TITLE
关于指纹去重的算法准确率？

### ISSUE THREAD

**Issue by huyanping** [NLPchina/nlp-lang#19]
方便提供指纹去重的准确率吗？

**Comment by ansjsun** [comment]
这个没有过统计.一般用途是基本一致的文章效果会好一些

**Comment by huyanping** [comment]
是否可以考虑把simhash算法加入到nlp-lang中？

**Comment by ansjsun** [comment]
增加simhash 支持 

https://github.com/NLPchina/nlp-lang/commit/15aa008617edb78027a08a9086451f1a23ab775a

你可以参看例子

https://github.com/NLPchina/nlp-lang/blob/master/src/test/java/org/nlpcn/commons/lang/finger/SimHashServiceTest.java

**Comment by ansjsun** [comment]
只实现了simhash的计算， 目前并没有实现。simhash的search功能。。那块可能比较麻烦，并且设计到存储。如果有必要也可以实现。。

**Comment by huyanping** [comment]
谢谢
