### ISSUE TITLE
f2j('尼日利亚')  => '尼日尔利亚'

### ISSUE THREAD

**Issue by Poordeveloper** [NLPchina/nlp-lang#24]
还有诸如巴基斯坦等等都有这样的问题
巴基斯坦　＝》 巴基斯坦斯坦
厄瓜多尔   =》 厄瓜多尔 尔

**Comment by ansjsun** [comment]
你好这个问题的确存在
是因为词典中 simplified.txt
存在
````
厄瓜多=厄瓜多尔 
````

增加一条记录

````
厄瓜多尔=厄瓜多尔
厄瓜多=厄瓜多尔
````

就解决了..会在下一个版本中修复此问题..在这之前只能手动打这个补丁了
