### ISSUE TITLE
http://maven.nlpcn.org/org/nlpcn/nlp-lang/ 无法访问

### ISSUE THREAD

**Issue by rmrf** [NLPchina/nlp-lang#30]
地址更换了么？

**Comment by rmrf** [comment]
https://mvnrepository.com/artifact/org.nlpcn/nlp-lang 使用这个地址了么？能否把以前1.5 的版本也放上去呢？谢谢！

**Comment by rmrf** [comment]
@ansjsun

**Comment by ansjsun** [comment]
@rmrf  十分抱歉 1.5的jar包代码都不好找了...已经没有了额...所以放不了了

**Comment by rmrf** [comment]
已经切换到了`mvnrepository.com`这个地址了，以前的`maven.nlpcn.org` 不再用了？

**Comment by ansjsun** [comment]
http://maven.nlpcn.org/ 旧的jar在这上面保留.以后新jar只在中央仓库发布.这里面就不发布了.

**Comment by rmrf** [comment]
好的，谢谢
