### ISSUE TITLE
如何加载自定义词典？

### ISSUE THREAD

**Issue by jiyzhang** [NLPchina/nlp-lang#31]
ansj加载自定义词典

尝试修改了library.properties, 添加了自定义词典
================================
#path of userLibrary this is default library
dic=library/default.dic

# user defined dictionary
dic_name=library/name.dic
dic_company=library/company.dic
dic_term=library/term.dic

#redress dic file path
ambiguityLibrary=library/ambiguity.dic
stop_dic1=library/stop.dic
synonymsLibrary=library/synonyms.dic
#set real name
isRealName=true

#isNameRecognition default true
isNameRecognition=true

#isNumRecognition default true
isNumRecognition=true

#digital quantifier merge default true
isQuantifierRecognition=true
================================

测试程序启动时，也找到了对应的词典文件
================================
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: **init dic_term to env value is : library/term.dic**
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init stop_dic1 to env value is : library/stop.dic
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: **init dic_name to env value is : library/name.dic**
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init ambiguityLibrary to env value is : library/ambiguity.dic
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init isQuantifierRecognition to env value is : true
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: **init dic_company to env value is : library/company.dic**
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init isRealName to env value is : true
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init synonymsLibrary to env value is : library/synonyms.dic
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init isNumRecognition to env value is : true
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init isNameRecognition to env value is : true
六月 17, 2017 2:49:30 下午 org.ansj.util.MyStaticValue info
信息: init dic to env value is : library/default.dic
六月 17, 2017 2:49:30 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
六月 17, 2017 2:49:30 下午 org.ansj.library.AmbiguityLibrary info
信息: load dic use time:1 path is : library/ambiguity.dic
六月 17, 2017 2:49:30 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/default.dic
六月 17, 2017 2:49:31 下午 org.ansj.library.DicLibrary info
信息: load dic use time:1249 path is : library/default.dic
六月 17, 2017 2:49:32 下午 org.ansj.library.DATDictionary info
信息: init core library ok use time : 736
六月 17, 2017 2:49:32 下午 org.ansj.library.NgramLibrary info
信息: init ngram ok use time :510
================================

分词使用的是 DictAnalysis: 
Result terms = DicAnalysis.parse(sent1);

但分词结果一直没有变化，实在是找不到原因了，还望大侠解救。

环境如下:
OS: macOS 10.12.5
JDK: 1.8.0_65
ansj-seg: 5.1.2
nlp-lang: 1.7.2

BTW, 使用 DictLibrary.insert添加新词后没问题。

**Comment by shi-yuan** [comment]
配置了，但是没使用，词典没生效，试试：
```java
DicAnalysis.parse(sent1, DicLibrary.gets("dic_name", "dic_company", "dic_term"))
```

**Comment by jiyzhang** [comment]
非常感谢，使用上面的语句，自定义词典已经生效
