### ISSUE TITLE
object of the same name as the administrative directory

### ISSUE THREAD

**Issue by luyee** [NLPchina/nlp-lang#4]
svn: Failed to add directory 'E:\Search\eclipse-luna\workspace\nlp-lang\src\main\java\org\nlpcn\commons\lang\finger\util\.svn': object of the same name as the administrative directory ,src\main\java\org\nlpcn\commons\lang\finger\util\下的.svn文件

**Comment by ansjsun** [comment]
可能是 因为别人提交错svn文件了。。现在应该删除了
