### ISSUE TITLE
动态插入重复的词会发生什么？会不会导致内存溢出？

### ISSUE THREAD

**Issue by ZhangChHao** [NLPchina/nlp-lang#43]
例如此类代码：
for(ini i=0;i<100000;i++){
   Pinyin.insertPinyin("疾风传",new String[]{"ji","feng","zhuan"});
}
是会后面的覆盖前面的？还是一直插入导致内存溢出？

**Comment by ZhangChHao** [comment]
我尝试修改源码以定时任务的方式，支持动态更新词库的功能，但是害怕插入相同的词导致内存溢出。

**Comment by ansjsun** [comment]
后面覆盖前面的， 不会溢出。。但是你可能要考虑并发安全。。

**Comment by ZhangChHao** [comment]
我会在拼音转换的方法和动态写入方法加上读写锁，使他们互斥从而解决并发问题，毕竟是读多写少，大多数时候不会产生锁争用的问题。
