### ISSUE TITLE
nlpcn demo上演示的复杂功能会开源吗?

### ISSUE THREAD

**Issue by ahkimkoo** [NLPchina/nlp-lang#5]
nlpcn demo上演示的关键词提取,情感趋向等复杂功能会开源么?如果开源大概会在什么时候放出?

**Comment by wangwenbincom** [comment]
nlpcn demo上演示的关键词提取,情感趋向等复杂功能会开源么?如果开源大概会在什么时候放出?

**Comment by ansjsun** [comment]
只要是上面显示的demo都可以开源。但是现在做的还不是很满意。所以没有开放出来。前一段时间投入到另一个项目中。没有持续维护本项目。现在基本办妥。会在上面继续投入精力。。希望能越做越好
