### ISSUE TITLE
Trie not Tire

### ISSUE THREAD

**Issue by atealxt** [NLPchina/nlp-lang#6]
是Trie不是Tire，对吧？貌似笔误了。

**Comment by ansjsun** [comment]
是的 。。错了好多年了。。干脆就不改了吧。。。一步错步步错。。现在改了无法向前兼容了：（

**Comment by node** [comment]
处女座同样非常介意这一点儿，哈哈； 不如开个分支吧 :)

**Comment by ansjsun** [comment]
我也处女座。额。。node 兄有兴趣可以考虑分支。。小弟力不从心了哎

**Comment by node** [comment]
拼写错误已经全部修正了，提交了pull :)   @ansjsun
